version: '3'

services:
  wordpress:
    image: wordpress
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    links:
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: mariadb
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database:/var/lib/mysql
